import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque, Instrument_Sans } from "next/font/google";
import "./globals.css";
import { SITE_DESCRIPTION, SITE_NAME, siteUrl } from "@/lib/seo";

/**
 * The document itself, and nothing else.
 *
 * The universe chrome (star field, HUD, menu, the travelling camera) lives in app/(site)/layout.tsx,
 * so /admin — a tool, not a scene — never loads or renders any of it. Route groups do not appear in
 * URLs, so every public path is exactly what it was.
 */

const display = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const body = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  // Absolute origin for Open Graph, canonicals and the sitemap. See lib/seo.ts.
  metadataBase: new URL(siteUrl()),
  // Pages set only their own part; "| JYC" is appended here.
  title: { default: "JYC | Jaypee Youth Club", template: "%s | JYC" },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: ["Jaypee Youth Club", "JYC", "JIIT", "student clubs", "technical", "music", "events"],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: "JYC | Jaypee Youth Club",
    description: SITE_DESCRIPTION,
    url: "/",
    locale: "en_IN",
    // The card itself is generated by app/opengraph-image.tsx (and per-club / per-event twins).
  },
  twitter: { card: "summary_large_image", title: "JYC | Jaypee Youth Club", description: SITE_DESCRIPTION },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } },
  icons: { icon: "/jyc-logo.png", apple: "/jyc-logo.png" },
};

export const viewport: Viewport = {
  themeColor: "#0b0c0c",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable}`}>
      <body className="bg-void font-body text-bone antialiased">{children}</body>
    </html>
  );
}
