-- JYC Universe: seed. GENERATED by scripts/generate-seed.ts from lib/sample.ts. Do not hand-edit.
-- Run AFTER supabase/schema.sql. Safe to re-run: rows with a key are upserted, and list rows
-- (team, achievements, gallery, about) of the seeded clubs are replaced. That resets sample edits to those clubs.
-- Everything here is PLACEHOLDER content (see lib/sample.ts).

begin;

-- domains
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('technical', 'TECHNICAL', 'Where ideas get built', 'Circuits, code and things that move. A city that never fully switches off, where a late-night idea becomes a working prototype.', '#5fd4c4', 'circuit', 240, 250, '[[-70,-30],[-20,-55],[40,-40],[75,0],[20,35],[-45,45]]'::jsonb, '[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[1,4]]'::jsonb, '[[-143,-7,1.4],[-148,-66,1.3],[126,48,1.4],[-132,30,1.6],[-138,53,1.4],[57,64,1],[-101,54,1.3],[104,75,1.3],[-153,60,1.6]]'::jsonb, 26, -18, 0)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('music', 'MUSIC', 'Feel the frequency', 'A district that runs on rhythm: rehearsal rooms, open stages and jam sessions that outlast the last bus home.', '#f5a23a', 'pulse', 610, 120, '[[-90,10],[-45,-30],[0,20],[45,-25],[90,15],[0,-62]]'::jsonb, '[[0,1],[1,2],[2,3],[3,4],[1,5],[3,5]]'::jsonb, '[[81,37,1.4],[-42,80,0.9],[-186,-10,1.6],[161,6,0.9],[162,68,1.6],[-162,20,0.8],[-149,32,1.8],[40,119,1],[61,109,0.9]]'::jsonb, 28, 12, 1)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('dance', 'DANCE', 'Move the story', 'Motion as language. Choreography, freestyle and fusion, from the first count to the final bow.', '#ee5a7a', 'flow', 960, 280, '[[-80,30],[-50,-20],[-5,-50],[40,-30],[75,10],[50,50]]'::jsonb, '[[0,1],[1,2],[2,3],[3,4],[4,5]]'::jsonb, '[[-190,-14,0.7],[-7,-76,1.3],[83,116,1.4],[-150,2,1.6],[28,113,1.7],[138,-87,0.9],[-134,-68,0.8],[-104,12,1.4],[-57,109,1]]'::jsonb, 26, -30, 2)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('sports', 'SPORTS', 'Play at full speed', 'Teams, tournaments and early-morning practice. A world built around momentum, effort and the next match.', '#b4dc4f', 'dynamic', 930, 545, '[[-70,40],[-30,0],[10,-40],[60,-55],[30,10],[70,40]]'::jsonb, '[[0,1],[1,2],[2,3],[1,4],[4,5],[2,4]]'::jsonb, '[[84,-79,1.4],[-170,-31,1.2],[115,-48,0.8],[-44,-117,1.1],[-101,109,1.1],[27,79,1.5],[44,-78,1],[-108,-20,1.1],[81,78,1]]'::jsonb, 27, 24, 3)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('literary', 'LITERARY', 'Words with weight', 'Debate, poetry, writing and the quiet thrill of the right sentence. Atmospheric, unhurried, full of margins.', '#e8e0cc', 'ink', 585, 680, '[[-70,-20],[-30,-40],[0,-15],[30,-40],[70,-20],[0,40]]'::jsonb, '[[0,1],[1,2],[2,3],[3,4],[0,5],[5,4],[2,5]]'::jsonb, '[[159,47,0.8],[96,-15,1.3],[150,53,1.3],[149,-31,1.7],[-17,-120,1.8],[-92,-35,1.6],[121,53,1.2],[161,-39,1.6],[26,109,1.2]]'::jsonb, 25, -8, 4)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;
insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values ('cultural', 'CULTURAL', 'Roots, retold', 'Theatre, art and traditions carried into new forms. A warm, heritage-rich quarter that keeps the campus story alive.', '#d0603f', 'heritage', 265, 540, '[[-60,40],[-60,-10],[0,-50],[60,-10],[60,40],[0,-10]]'::jsonb, '[[0,1],[1,2],[2,3],[3,4],[2,5],[1,5],[3,5]]'::jsonb, '[[132,-10,1.3],[-118,23,1.5],[-129,-9,1.5],[95,81,1.1],[52,-76,0.9],[-110,79,0.8],[-49,94,1.4],[-72,46,1.3],[-66,51,1.6]]'::jsonb, 27, 16, 5)
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,
  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,
  tilt = excluded.tilt, sort = excluded.sort;

-- collaborations
insert into public.collaborations (domain_a, domain_b, sort) values ('technical', 'music', 0) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('music', 'dance', 1) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('dance', 'sports', 2) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('dance', 'cultural', 3) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('cultural', 'literary', 4) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('technical', 'literary', 5) on conflict (domain_a, domain_b) do update set sort = excluded.sort;
insert into public.collaborations (domain_a, domain_b, sort) values ('technical', 'cultural', 6) on conflict (domain_a, domain_b) do update set sort = excluded.sort;

-- clubs
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('dice', 'technical', 'DICE', 'Roll the idea.', 'Ideas go on the table, get tested against each other and come out as something real. A room for the curious, the stubborn and the slightly reckless.', 0)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('dsc', 'technical', 'DSC', 'Learn it. Build it. Share it.', 'A community of student developers who learn in public: study jams, shared projects and the kind of help that starts with ''let me show you''.', 1)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('cice', 'technical', 'CICE', 'Signals, circuits, systems.', 'Where electronics meets curiosity. Boards on the bench, oscilloscopes humming and a steady supply of things that blink, buzz or finally work.', 2)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('robotics', 'technical', 'Robotics', 'Machines that move.', 'Motors, sensors and a workshop that never really closes. From line followers to arms that pick things up, this is where code learns to push back against gravity.', 3)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('coding', 'technical', 'Coding', 'Ship it before sunrise.', 'Late nights, strong opinions about tabs and spaces, and a lot of pull requests. Contests, hack nights and the quiet satisfaction of a green build.', 4)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('band', 'music', 'Band', 'Loud, live, together.', 'Description coming soon.', 5)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('vocals', 'music', 'Vocals', 'Find your voice.', 'Description coming soon.', 6)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('instrumentals', 'music', 'Instrumentals', 'Strings, keys, brass and skins.', 'Description coming soon.', 7)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('dj', 'music', 'DJ', 'Blend the room.', 'Description coming soon.', 8)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('dance-crew', 'dance', 'Dance Crew', 'Dance club', 'Description coming soon.', 9)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('football', 'sports', 'Football', 'Sports club', 'Description coming soon.', 10)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('cricket', 'sports', 'Cricket', 'Sports club', 'Description coming soon.', 11)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('literary-society', 'literary', 'Literary Society', 'Literary club', 'Description coming soon.', 12)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('debate', 'literary', 'Debate', 'Literary club', 'Description coming soon.', 13)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('drama', 'cultural', 'Drama', 'Cultural club', 'Description coming soon.', 14)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;
insert into public.clubs (id, domain_id, name, tagline, description, sort) values ('fine-arts', 'cultural', 'Fine Arts', 'Cultural club', 'Description coming soon.', 15)
on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;

-- coordinators, achievements, gallery_items (replaced per club)
delete from public.coordinators where club_id in ('dice', 'dsc', 'cice', 'robotics', 'coding', 'band', 'vocals', 'instrumentals', 'dj', 'dance-crew', 'football', 'cricket', 'literary-society', 'debate', 'drama', 'fine-arts');
delete from public.achievements where club_id in ('dice', 'dsc', 'cice', 'robotics', 'coding', 'band', 'vocals', 'instrumentals', 'dj', 'dance-crew', 'football', 'cricket', 'literary-society', 'debate', 'drama', 'fine-arts');
delete from public.gallery_items where club_id in ('dice', 'dsc', 'cice', 'robotics', 'coding', 'band', 'vocals', 'instrumentals', 'dj', 'dance-crew', 'football', 'cricket', 'literary-society', 'debate', 'drama', 'fine-arts');
insert into public.coordinators (club_id, sort, name, role, photo) values ('dice', 0, 'Name to be added', 'Head coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dice', 1, 'Name to be added', 'Co-coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dice', 2, 'Name to be added', 'Technical lead', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dice', 3, 'Name to be added', 'Design lead', null);
insert into public.achievements (club_id, sort, year, title, detail) values ('dice', 0, 2026, 'Sample: inter-college finalist', 'Replace with a real milestone from this club''s story.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dice', 1, 2026, 'Sample: flagship workshop series', 'A line or two about what happened and who took part.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dice', 2, 2025, 'Sample: first campus showcase', 'Placeholder text. Add the real detail here.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dice', 3, 2024, 'Sample: club founded', 'Every timeline starts somewhere.');
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 0, '', 'Placeholder photo 1', 400, 500);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 1, '', 'Placeholder photo 2', 300, 200);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 2, '', 'Placeholder photo 3', 100, 100);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 3, '', 'Placeholder photo 4', 300, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 4, '', 'Placeholder photo 5', 400, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 5, '', 'Placeholder photo 6', 200, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 6, '', 'Placeholder photo 7', 500, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dice', 7, '', 'Placeholder photo 8', 100, 100);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dsc', 0, 'Name to be added', 'Head coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dsc', 1, 'Name to be added', 'Co-coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dsc', 2, 'Name to be added', 'Technical lead', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('dsc', 3, 'Name to be added', 'Design lead', null);
insert into public.achievements (club_id, sort, year, title, detail) values ('dsc', 0, 2026, 'Sample: inter-college finalist', 'Replace with a real milestone from this club''s story.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dsc', 1, 2026, 'Sample: flagship workshop series', 'A line or two about what happened and who took part.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dsc', 2, 2025, 'Sample: first campus showcase', 'Placeholder text. Add the real detail here.');
insert into public.achievements (club_id, sort, year, title, detail) values ('dsc', 3, 2024, 'Sample: club founded', 'Every timeline starts somewhere.');
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 0, '', 'Placeholder photo 1', 400, 500);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 1, '', 'Placeholder photo 2', 300, 200);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 2, '', 'Placeholder photo 3', 100, 100);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 3, '', 'Placeholder photo 4', 300, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 4, '', 'Placeholder photo 5', 400, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 5, '', 'Placeholder photo 6', 200, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 6, '', 'Placeholder photo 7', 500, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('dsc', 7, '', 'Placeholder photo 8', 100, 100);
insert into public.coordinators (club_id, sort, name, role, photo) values ('cice', 0, 'Name to be added', 'Head coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('cice', 1, 'Name to be added', 'Co-coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('cice', 2, 'Name to be added', 'Technical lead', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('cice', 3, 'Name to be added', 'Design lead', null);
insert into public.achievements (club_id, sort, year, title, detail) values ('cice', 0, 2026, 'Sample: inter-college finalist', 'Replace with a real milestone from this club''s story.');
insert into public.achievements (club_id, sort, year, title, detail) values ('cice', 1, 2026, 'Sample: flagship workshop series', 'A line or two about what happened and who took part.');
insert into public.achievements (club_id, sort, year, title, detail) values ('cice', 2, 2025, 'Sample: first campus showcase', 'Placeholder text. Add the real detail here.');
insert into public.achievements (club_id, sort, year, title, detail) values ('cice', 3, 2024, 'Sample: club founded', 'Every timeline starts somewhere.');
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 0, '', 'Placeholder photo 1', 400, 500);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 1, '', 'Placeholder photo 2', 300, 200);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 2, '', 'Placeholder photo 3', 100, 100);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 3, '', 'Placeholder photo 4', 300, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 4, '', 'Placeholder photo 5', 400, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 5, '', 'Placeholder photo 6', 200, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 6, '', 'Placeholder photo 7', 500, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('cice', 7, '', 'Placeholder photo 8', 100, 100);
insert into public.coordinators (club_id, sort, name, role, photo) values ('robotics', 0, 'Name to be added', 'Head coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('robotics', 1, 'Name to be added', 'Co-coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('robotics', 2, 'Name to be added', 'Technical lead', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('robotics', 3, 'Name to be added', 'Design lead', null);
insert into public.achievements (club_id, sort, year, title, detail) values ('robotics', 0, 2026, 'Sample: inter-college finalist', 'Replace with a real milestone from this club''s story.');
insert into public.achievements (club_id, sort, year, title, detail) values ('robotics', 1, 2026, 'Sample: flagship workshop series', 'A line or two about what happened and who took part.');
insert into public.achievements (club_id, sort, year, title, detail) values ('robotics', 2, 2025, 'Sample: first campus showcase', 'Placeholder text. Add the real detail here.');
insert into public.achievements (club_id, sort, year, title, detail) values ('robotics', 3, 2024, 'Sample: club founded', 'Every timeline starts somewhere.');
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 0, '', 'Placeholder photo 1', 400, 500);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 1, '', 'Placeholder photo 2', 300, 200);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 2, '', 'Placeholder photo 3', 100, 100);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 3, '', 'Placeholder photo 4', 300, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 4, '', 'Placeholder photo 5', 400, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 5, '', 'Placeholder photo 6', 200, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 6, '', 'Placeholder photo 7', 500, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('robotics', 7, '', 'Placeholder photo 8', 100, 100);
insert into public.coordinators (club_id, sort, name, role, photo) values ('coding', 0, 'Name to be added', 'Head coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('coding', 1, 'Name to be added', 'Co-coordinator', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('coding', 2, 'Name to be added', 'Technical lead', null);
insert into public.coordinators (club_id, sort, name, role, photo) values ('coding', 3, 'Name to be added', 'Design lead', null);
insert into public.achievements (club_id, sort, year, title, detail) values ('coding', 0, 2026, 'Sample: inter-college finalist', 'Replace with a real milestone from this club''s story.');
insert into public.achievements (club_id, sort, year, title, detail) values ('coding', 1, 2026, 'Sample: flagship workshop series', 'A line or two about what happened and who took part.');
insert into public.achievements (club_id, sort, year, title, detail) values ('coding', 2, 2025, 'Sample: first campus showcase', 'Placeholder text. Add the real detail here.');
insert into public.achievements (club_id, sort, year, title, detail) values ('coding', 3, 2024, 'Sample: club founded', 'Every timeline starts somewhere.');
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 0, '', 'Placeholder photo 1', 400, 500);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 1, '', 'Placeholder photo 2', 300, 200);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 2, '', 'Placeholder photo 3', 100, 100);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 3, '', 'Placeholder photo 4', 300, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 4, '', 'Placeholder photo 5', 400, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 5, '', 'Placeholder photo 6', 200, 300);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 6, '', 'Placeholder photo 7', 500, 400);
insert into public.gallery_items (club_id, sort, src, alt, width, height) values ('coding', 7, '', 'Placeholder photo 8', 100, 100);

-- socials (only clubs that have some)

-- club_identity
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('dice', '#5fd4c4', 'pips', 'upper', 'solid', '-0.055em', false, 'The die', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('dsc', '#9cc9e6', 'mesh', 'upper', 'outline', '-0.03em', false, 'Twin towers', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('cice', '#7fdcae', 'rings', 'upper', 'solid', '-0.04em', false, 'The radar tower', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('robotics', '#f0a24a', 'gears', 'upper', 'solid', '-0.05em', false, 'The workshop', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('coding', '#c4e26e', 'code', 'lower', 'solid', '-0.045em', true, 'The code tower', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('band', '#f5a23a', 'waves', 'upper', 'solid', '-0.055em', false, 'The stage', null)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('vocals', '#ff9d6c', 'waves', 'lower', 'solid', '-0.05em', false, 'The studio', 8)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('instrumentals', '#e07f3a', 'rings', 'upper', 'outline', '-0.025em', false, 'The concert hall', 5)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;
insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values ('dj', '#ffd166', 'waves', 'upper', 'solid', '-0.07em', false, 'The record', 14)
on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,
  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;

-- events
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('open-mic-night', 'vocals', 'Open Mic Night', '2026-10-18', '6:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dice-roll-call', 'dice', 'Roll Call', '2026-10-09', '5:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dice-prototype-night', 'dice', 'Prototype Night', '2026-04-12', '6:30 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dice-pitch-lab', 'dice', 'Pitch Lab', '2025-11-22', '4:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dsc-study-jam', 'dsc', 'Study Jam', '2026-10-15', '4:30 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dsc-community-meetup', 'dsc', 'Community Meetup', '2026-03-07', '5:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('dsc-build-day', 'dsc', 'Build Day', '2025-09-27', '10:00 AM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('cice-circuit-clinic', 'cice', 'Circuit Clinic', '2026-11-05', '3:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('cice-solder-night', 'cice', 'Solder Night', '2026-02-19', '6:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('robotics-line-sprint', 'robotics', 'Line Follower Sprint', '2026-10-25', '11:00 AM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('robotics-arm-workshop', 'robotics', 'Arm Build Workshop', '2026-05-03', '10:00 AM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('robotics-bot-battle', 'robotics', 'Bot Battle', '2025-10-11', '2:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('hack-the-night', 'coding', 'Hack the Night', '2026-11-02', '9:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('coding-code-relay', 'coding', 'Code Relay', '2026-03-21', '3:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;
insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values ('coding-algo-league', 'coding', 'Algo League', '2025-12-06', '2:00 PM', 'To be announced', 'Sample event. Replace with real event data.', null, null)
on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,
  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;

-- city_spots (from the built-in layouts in lib/city.ts)
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('technical', 'coding', 'spire', 4.4, 0.6, 2.6, 2.6, 360)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('technical', 'robotics', 'workshop', 0.8, 3.6, 4.6, 3.2, 190)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('technical', 'dsc', 'twin', 9.6, 1, 5.8, 2.6, 300)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('technical', 'cice', 'tiered', 1.3, 9.7, 4.6, 4.6, 290)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('technical', 'dice', 'die', 10.2, 10, 4.6, 4.6, 190)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('music', 'band', 'stage', 9.2, 0.9, 6, 4.4, 250)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('music', 'vocals', 'studio', 0.9, 1.5, 5.2, 5, 215)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('music', 'instrumentals', 'hall', 1, 9.6, 5.2, 5, 250)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;
insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values ('music', 'dj', 'vinyl', 10.2, 10, 4.6, 4.6, 135)
on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;

-- about
delete from public.about_entries;
insert into public.about_entries (year, title, detail, sort) values (2016, 'Sample: an idea in a corridor', 'Replace with how JYC actually began and who was in the room.', 0);
insert into public.about_entries (year, title, detail, sort) values (2018, 'Sample: the club becomes official', 'A line or two on the first coordinators and the first event.', 1);
insert into public.about_entries (year, title, detail, sort) values (2020, 'Sample: the first worlds take shape', 'Technical and Music grow into communities of their own.', 2);
insert into public.about_entries (year, title, detail, sort) values (2023, 'Sample: the first inter-college fest', 'Placeholder text. Add the real detail here.', 3);
insert into public.about_entries (year, title, detail, sort) values (2025, 'Sample: six worlds, one club', 'Technical, Music, Dance, Sports, Literary and Cultural under one roof.', 4);
insert into public.about_entries (year, title, detail, sort) values (2026, 'Sample: the universe opens', 'This site: a place you travel through, not a page you scroll.', 5);
insert into public.site_settings (key, value) values ('about_intro', 'Placeholder. One short paragraph on who Jaypee Youth Club is, what it exists for, and what a student gets from it.') on conflict (key) do update set value = excluded.value;

commit;
