/**
 * Regenerates supabase/seed.sql from the local sample content.
 *
 *   npx tsx scripts/generate-seed.ts
 *
 * `npx` fetches tsx on demand; it is not a project dependency. supabase/seed.sql is committed, so you only
 * need this if you edit lib/sample.ts, lib/identity.ts or the spots in lib/city.ts and want the seed to follow.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getStaticCity } from "../lib/city";
import { identities } from "../lib/identity";
import { aboutIntro, aboutStory, clubs, collaborations, domains, events } from "../lib/sample";

const q = (v: string | number | boolean | null | undefined): string => {
  if (v === null || v === undefined || v === "") return v === "" ? "''" : "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${v.replace(/'/g, "''")}'`;
};
const j = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const list = (ids: string[]) => ids.map(q).join(", ");

const out: string[] = [];
const push = (...l: string[]) => out.push(...l);

push(
  "-- JYC Universe: seed. GENERATED by scripts/generate-seed.ts from lib/sample.ts. Do not hand-edit.",
  "-- Run AFTER supabase/schema.sql. Safe to re-run: rows with a key are upserted, and list rows",
  "-- (team, achievements, gallery, about) of the seeded clubs are replaced. That resets sample edits to those clubs.",
  "-- Everything here is PLACEHOLDER content (see lib/sample.ts).",
  "",
  "begin;",
  "",
);

// domains
push("-- domains");
domains.forEach((d, i) => {
  push(
    `insert into public.domains (id, name, tagline, description, accent, atmosphere, pos_x, pos_y, stars, links, dust, planet_radius, tilt, sort) values (${[
      q(d.id), q(d.name), q(d.tagline), q(d.description), q(d.accent), q(d.atmosphere),
      d.position.x, d.position.y, j(d.stars), j(d.links), j(d.dust), d.planetRadius, d.tilt, i,
    ].join(", ")})`,
    "on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description,",
    "  accent = excluded.accent, atmosphere = excluded.atmosphere, pos_x = excluded.pos_x, pos_y = excluded.pos_y,",
    "  stars = excluded.stars, links = excluded.links, dust = excluded.dust, planet_radius = excluded.planet_radius,",
    "  tilt = excluded.tilt, sort = excluded.sort;",
  );
});

push("", "-- collaborations");
collaborations.forEach(([a, b], i) => {
  push(`insert into public.collaborations (domain_a, domain_b, sort) values (${q(a)}, ${q(b)}, ${i}) on conflict (domain_a, domain_b) do update set sort = excluded.sort;`);
});

// clubs
push("", "-- clubs");
clubs.forEach((c, i) => {
  push(
    `insert into public.clubs (id, domain_id, name, tagline, description, sort) values (${[q(c.id), q(c.domain), q(c.name), q(c.tagline), q(c.description), i].join(", ")})`,
    "on conflict (id) do update set domain_id = excluded.domain_id, name = excluded.name, tagline = excluded.tagline, description = excluded.description, sort = excluded.sort;",
  );
});

const clubIds = clubs.map((c) => c.id);

push("", "-- coordinators, achievements, gallery_items (replaced per club)");
push(`delete from public.coordinators where club_id in (${list(clubIds)});`);
push(`delete from public.achievements where club_id in (${list(clubIds)});`);
push(`delete from public.gallery_items where club_id in (${list(clubIds)});`);
for (const c of clubs) {
  c.coordinators.forEach((p, i) =>
    push(`insert into public.coordinators (club_id, sort, name, role, photo) values (${[q(c.id), i, q(p.name), q(p.role), q(p.photo)].join(", ")});`),
  );
  c.achievements.forEach((a, i) =>
    push(`insert into public.achievements (club_id, sort, year, title, detail) values (${[q(c.id), i, a.year, q(a.title), q(a.detail)].join(", ")});`),
  );
  c.gallery.forEach((g, i) =>
    push(`insert into public.gallery_items (club_id, sort, src, alt, width, height) values (${[q(c.id), i, q(g.src), q(g.alt), q(g.width), q(g.height)].join(", ")});`),
  );
}

push("", "-- socials (only clubs that have some)");
for (const c of clubs) {
  const s = c.socials;
  if (!s.instagram && !s.linkedin && !s.email && !s.website) continue;
  push(
    `insert into public.socials (club_id, instagram, linkedin, email, website) values (${[q(c.id), q(s.instagram), q(s.linkedin), q(s.email), q(s.website)].join(", ")})`,
    "on conflict (club_id) do update set instagram = excluded.instagram, linkedin = excluded.linkedin, email = excluded.email, website = excluded.website;",
  );
}

push("", "-- club_identity");
for (const [clubId, id] of Object.entries(identities)) {
  if (!clubIds.includes(clubId)) continue;
  push(
    `insert into public.club_identity (club_id, accent, motif, title_case, title_style, tracking, cursor, city_note, hero_seed) values (${[
      q(clubId), q(id.accent), q(id.motif), q(id.titleCase), q(id.titleStyle), q(id.tracking), q(Boolean(id.cursor)), q(id.cityNote), q(id.heroSeed),
    ].join(", ")})`,
    "on conflict (club_id) do update set accent = excluded.accent, motif = excluded.motif, title_case = excluded.title_case, title_style = excluded.title_style,",
    "  tracking = excluded.tracking, cursor = excluded.cursor, city_note = excluded.city_note, hero_seed = excluded.hero_seed;",
  );
}

push("", "-- events");
for (const e of events) {
  push(
    `insert into public.events (id, club_id, title, date, time, location, description, poster, registration_url) values (${[
      q(e.id), q(e.clubId), q(e.title), q(e.date), q(e.time), q(e.location), q(e.description), q(e.poster), q(e.registrationUrl),
    ].join(", ")})`,
    "on conflict (id) do update set club_id = excluded.club_id, title = excluded.title, date = excluded.date, time = excluded.time,",
    "  location = excluded.location, description = excluded.description, poster = excluded.poster, registration_url = excluded.registration_url;",
  );
}

push("", "-- city_spots (from the built-in layouts in lib/city.ts)");
for (const d of domains) {
  const city = getStaticCity(d.id);
  if (!city) continue;
  for (const s of city.spots) {
    push(
      `insert into public.city_spots (domain_id, club_id, silhouette, gx, gy, w, d, height) values (${[
        q(d.id), q(s.clubId), q(s.silhouette), s.gx, s.gy, s.w, s.d, s.height,
      ].join(", ")})`,
      "on conflict (domain_id, club_id) do update set silhouette = excluded.silhouette, gx = excluded.gx, gy = excluded.gy, w = excluded.w, d = excluded.d, height = excluded.height;",
    );
  }
}

push("", "-- about");
push("delete from public.about_entries;");
aboutStory.forEach((a, i) =>
  push(`insert into public.about_entries (year, title, detail, sort) values (${[a.year, q(a.title), q(a.detail), i].join(", ")});`),
);
push(`insert into public.site_settings (key, value) values ('about_intro', ${q(aboutIntro)}) on conflict (key) do update set value = excluded.value;`);

push("", "commit;", "");

const target = resolve(__dirname, "../supabase/seed.sql");
writeFileSync(target, out.join("\n"));
console.log(`wrote ${target} (${out.length} lines)`);
